apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: order-build
  name: order-build
  namespace: ngfs-core-framework
spec:
  failedBuildsHistoryLimit:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'order:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: Binary
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'openjdk:8-jdk-alpine'
    type: Docker